### ISSUE TITLE
Cannot open libclang.dll on Windows when LIBCLANG_PATH is specified

### ISSUE THREAD

**Issue by xzn** [KyleMayes/clang-sys#105]
```
Error: Custom { kind: InvalidInput, error: "the `libclang` shared library at D:\\Compilers\\msys64\\mingw64\\bin\\libclang.dll could not be opened: The specified module could not be found. (os error 126)" }
```

Using clang from msys2 install, since I'm cross-compiling, I'm trying to set LIBCLANG_PATH to either mingw32's clang or mingw64's clang. Without LIBCLANG_PATH set this crate compiles, otherwise it finds the dll but cannot open it?

Edit: I have `runtime` feature specified.

**Comment by xzn** [comment]
`lib.rs`:
```rust
use clang::{Clang};
use std::io::{Error, ErrorKind, Result};

pub fn clang() -> Result<()> {
	Clang::new().map_err(|e| Error::new(ErrorKind::InvalidInput, e))?;
	Ok(())
}

pub fn clang_sys() -> Result<()> {
	clang_sys::load().map_err(|e| Error::new(ErrorKind::InvalidInput, e))?;
	Ok(())
}

#[cfg(test)]
mod tests {
    use crate::*;

    #[test]
    fn clang_test() -> Result<()> {
		clang()?;
		clang_sys()
    }
}
```

`Cargo.toml`:
```toml
[package]
name = "clang_sys_test"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
clang = { version = "0.23", features = ["runtime", "clang_8_0"] }
clang-sys = { version = "0.28", features = ["runtime", "clang_8_0"] }
```
